### ISSUE TITLE
mac编译报错。

### ISSUE THREAD

**Issue by gameboy68** [tux116/navicat-keygen#1]
ld: library not found for -lplist++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [patcher] Error 1

**Comment by momo-cn** [comment]
+1

**Comment by tux116** [comment]
check new release [https://github.com/tux116/navicat-keygen/releases/tag/v4.3.1](https://github.com/tux116/navicat-keygen/releases/tag/v4.3.1) macOS x64 version
