### ISSUE TITLE
MacOS 编译错误

### ISSUE THREAD

**Issue by gameboy68** [tux116/navicat-keygen#3]
g++ -std=c++17 -O2 \
-I./common/ \
-I/usr/local/opt/openssl@1.1/include -L/usr/local/opt/openssl@1.1/lib \
  \
  \
  \
./navicat-patcher/CapstoneDisassembler.cpp ./navicat-patcher/KeystoneAssembler.cpp ./navicat-patcher/Misc.cpp ./navicat-patcher/X64ImageInterpreter.cpp ./navicat-patcher/PatchSolution0.cpp ./navicat-patcher/PatchSolution1.cpp ./navicat-patcher/PatchSolution2.cpp ./navicat-patcher/PatchSolution3.cpp ./navicat-patcher/main.cpp -o ./bin/navicat-patcher -lcrypto -lcapstone -lkeystone -lplist++
ld: library not found for -lplist++
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [patcher] Error 1

**Comment by tux116** [comment]
`https://github.com/tux116/navicat-keygen/issues/1#issuecomment-1118135851`
